language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc
    - CCACHE=1

matrix:
  include:
    # Ubuntu 20.04 GCC 9.3.0
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-20.04 DEFCONFIG=ppc64le
      name: "Ubuntu 20.04 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc64
      name: "Ubuntu 20.04 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet64_smp
      name: "Ubuntu 20.04 kernel: corenet64_smp (PPC_BOOK3E_64)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=pmac32
      name: "Ubuntu 20.04 kernel: pmac32 (PPC_BOOK3S_32)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc40x
      name: "Ubuntu 20.04 kernel: ppc40x (PPC_40x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc44x
      name: "Ubuntu 20.04 kernel: ppc44x (PPC_44x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=mpc885_ads
      name: "Ubuntu 20.04 kernel: mpc885_ads (PPC_8xx)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet32_smp
      name: "Ubuntu 20.04 kernel: corenet32_smp (PPC_85xx)"

    # Ubuntu 20.04 clang
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-20.04 DEFCONFIG=ppc64le
    #  name: "clang 10 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc64
    #  name: "clang 10 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    # /linux/arch/powerpc/lib/xor_vmx.c:119:6: error: stack frame size of 1344 bytes in function '__xor_altivec_5' [-Werror,-Wframe-larger-than=]
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet64_smp
    #  name: "clang 10 kernel: corenet64_smp (PPC_BOOK3E_64)"
    # /linux/arch/powerpc/lib/xor_vmx.c:119:6: error: stack frame size of 1232 bytes in function '__xor_altivec_5' [-Werror,-Wframe-larger-than=]
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=pmac32
    #  name: "clang 10 kernel: pmac32 (PPC_BOOK3S_32)"
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc40x
    #  name: "clang 10 kernel: ppc40x (PPC_40x)"
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=ppc44x
    #  name: "clang 10 kernel: ppc44x (PPC_44x)"
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=mpc885_ads
    #  name: "clang 10 kernel: mpc885_ads (PPC_8xx)"
    # /linux/arch/powerpc/platforms/85xx/corenet_generic.c:210:1: error: attribute declaration must precede definition [-Werror,-Wignored-attributes]
    #- os:   linux
    #  arch: amd64
    #  env:  CLANG=1 TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-20.04 DEFCONFIG=corenet32_smp
    #  name: "clang 10 kernel: corenet32_smp (PPC_85xx)"

    # Fedora 32 GCC 10.1.1
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=fedora-32 DEFCONFIG=ppc64le
      name: "Fedora 32 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=ppc64
      name: "Fedora 32 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=corenet64_smp
      name: "Fedora 32 kernel: corenet64_smp (PPC_BOOK3E_64)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=pmac32
      name: "Fedora 32 kernel: pmac32 (PPC_BOOK3S_32)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=ppc40x
      name: "Fedora 32 kernel: ppc40x (PPC_40x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=ppc44x
      name: "Fedora 32 kernel: ppc44x (PPC_44x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=mpc885_ads
      name: "Fedora 32 kernel: mpc885_ads (PPC_8xx)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=fedora-32 DEFCONFIG=corenet32_smp
      name: "Fedora 32 kernel: corenet32_smp (PPC_85xx)"

    # kernel.org GCC 10
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64le IMAGE=korg-10.1.0 DEFCONFIG=ppc64le
    #  name: "GCC 10.1.0 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=ppc64
    #  name: "GCC 10.1.0 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=corenet64_smp
    #  name: "GCC 10.1.0 kernel: corenet64_smp (PPC_BOOK3E_64)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=pmac32
    #  name: "GCC 10.1.0 kernel: pmac32 (PPC_BOOK3S_32)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=ppc40x
    #  name: "GCC 10.1.0 kernel: ppc40x (PPC_40x)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=ppc44x
    #  name: "GCC 10.1.0 kernel: ppc44x (PPC_44x)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=mpc885_ads
    #  name: "GCC 10.1.0 kernel: mpc885_ads (PPC_8xx)"
    #- os:   linux
    #  arch: amd64
    #  env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-10.1.0 DEFCONFIG=corenet32_smp
    #  name: "GCC 10.1.0 kernel: corenet32_smp (PPC_85xx)"

    # kernel.org GCC 5.5.0
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=korg-5.5.0 DEFCONFIG=ppc64le
      name: "GCC 5.5.0 kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"

    # kernel.org GCC 4.9.4 - BE only
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=ppc64
      name: "GCC 4.9.4 kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=corenet64_smp
      name: "GCC 4.9.4 kernel: corenet64_smp (PPC_BOOK3E_64)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=pmac32
      name: "GCC 4.9.4 kernel: pmac32 (PPC_BOOK3S_32)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=ppc40x
      name: "GCC 4.9.4 kernel: ppc40x (PPC_40x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=ppc44x
      name: "GCC 4.9.4 kernel: ppc44x (PPC_44x)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=mpc885_ads
      name: "GCC 4.9.4 kernel: mpc885_ads (PPC_8xx)"
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=korg-4.9.4 DEFCONFIG=corenet32_smp
      name: "GCC 4.9.4 kernel: corenet32_smp (PPC_85xx)"

    # Selftests
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-20.04
      name: "ppctests: ppc64le Ubuntu 20.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-18.04
      name: "ppctests: ppc64le Ubuntu 18.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-16.04
      name: "ppctests: ppc64le Ubuntu 16.04"
    - os:   linux
      arch: amd64
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-20.04
      name: "ppctests: ppc64 Ubuntu 20.04"
    - os:   linux
      arch: amd64
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-18.04
      name: "ppctests: ppc64 Ubuntu 18.04"
    - os:   linux
      arch: amd64
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-16.04
      name: "ppctests: ppc64 Ubuntu 16.04"
    - os:   linux
      arch: ppc64le
      env:  TARGET=selftests SUBARCH=ppc64le IMAGE=ubuntu-20.04
      name: "selftests: ppc64le Ubuntu 20.04"
    - os:   linux
      arch: amd64
      env:  TARGET=selftests SUBARCH=ppc64 IMAGE=ubuntu-20.04
      name: "selftests: ppc64 Ubuntu 20.04"

    # Sparse
    - os:   linux
      arch: amd64
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-20.04 DEFCONFIG=ppc64le SPARSE=1
      name: "sparse: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - mkdir -p $HOME/.ccache
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
